WebBackViewComponent.Web/Models/CarViewModel.cs
namespace WebBackViewComponent.Web.Models
{
    public class CarViewModel
    {
        public string Header { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public int Kilometers { get; set; }
        public int Year { get; set; }
        public double Price { get; set; }
        public string Image { get; set; }
    }
}

WebBackViewComponent.Web/Components/CarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebBackViewComponent.Web.Models;

namespace WebBackViewComponent.Web.Components
{
    public class CarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(CarViewModel model) => View(model);
    }
}

WebBackViewComponent.Web/Controllers/HomeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebBackViewComponent.Web.Services;

namespace WebBackViewComponent.Web.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index([FromServices]ICarService carService) => View(await carService.GetCars());
    }
}

WebBackViewComponent.Web/Views/Home/Index.cshtml
@model IEnumerable<WebBackViewComponent.Web.Models.CarViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="my-4">Biler til salg</h1>

@foreach (var car in Model)
{
    <div class="mb-3 w-100">
        @await Component.InvokeAsync("Car", car)
    </div>
}

WebBackViewComponent.Web/Views/Shared/Components/Car/Default.cshtml
@model WebBackViewComponent.Web.Models.CarViewModel

<div class="card">
    <div class="card-header">
        <h3>@Model.Header</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <img src="@Model.Image" asp-append-version="true" style="max-height: 200px; max-width: 200px"/>
            </div>
            <div class="col-md-9 mt-3 mt-md-0">
                <h5>
                    @Model.Type <span style="font-size: 75%">@Model.Model</span>
                </h5>
                <div>@Model.Year</div>
                <div>@Model.Kilometers.ToString("N0") km.</div>
                <div>
                    <span class="font-weight-bold">@Model.Price.ToString("C0")</span>
                </div>
            </div>
        </div>
    </div>
</div>

WebBackViewComponent.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car View Component</title>
    <link rel="stylesheet" href="~/libs/bootstrap/css/bootstrap.min.css" />
</head>
<body>
    <main class="container">
        @RenderBody()
    </main>

    <footer class="container">
        <hr />
        <p>&copy; 2019 - K7C</p>
    </footer>

    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/bootstrap/js/bootstrap.js"></script>
</body>
</html>